### ISSUE TITLE
Highlighted words background unable to read.

### ISSUE THREAD

**Issue by mayureshs** [DanKE123abc/RiderDarkTheme4VisualStudio#2]
The highlighted words background are unable to read. Can you please let me know the setting and value to change the background color for it ?

![image](https://github.com/DanKE123abc/RiderDarkTheme4VisualStudio/assets/1014702/4f9d1210-8912-4e24-9230-d1a448e0f2ab)

**Comment by DanKE123abc** [comment]
Sorry, this is just a fork, I don't know how to solve this problem.
forked form https://github.com/twintechresearch/Rider-Dark-Theme-For-Visual-Studio.git
